 - How collectors, copyright and the ephemeral nature of our hobby are contributing to the loss of our sub-cultural heritage.

# Intro
 -scholarship just beginning to start
  -peterson
  -documentaries
 -primary sources literally dying off
 -lots of popular material exists (print and pdf)
  -semi-popular material becoming easier to obtain because publishers starting to re-issue back catalogues as PDF
  -very early ephemeral material very hard to obtain
  -domesday book for example
   -a few issues held by libraries [atkatkatk], and while other issues are extant [atkatkatk] they are held privately and essentially inaccessable

# percieved value
 -Arneson collection almost lost
 -plagmada

# collectors
 -centralization
 -value escalation

# copyright
 -archive.org takedown of magazines

# conclusion
 -call for civil disobedience



It Belongs in a Museum!

Copyright

Ernie Gygax fire

do libraries value?

do collectors have appropriate insurance?

there was a story about a colletor scanning his rare items for his own reference before selling them off