 - How collectors, copyright and the ephemeral nature of our hobby are contributing to the loss of our sub-cultural heritage.

# Intro
 -scholarship just beginning to start
  -peterson
  -documentaries
  q

# percieved value
 -Arneson collection almost lost
 -plagmada

# collectors
 -centralization
 -value escalation

# copyright
 -archive.org takedown of magazines

# conclusion
 -call for civil disobedience



It Belongs in a Museum!

Copyright

Ernie Gygax fire

do libraries value?

