 - How collectors, copyright and the ephemeral nature of our hobby are contributing to the loss of our sub-cultural heritage.

# Intro
The RPG hobby is a young one. While wargames and bespoke examples existed earlier, it's probably safe to say that it was popularly born with the initial release of D&D 40 years ago (atk cite peterson).
 -our hobby is a young one
  -while wargames existed earlier it's safe to say that RPGs were poularly bord with the initial release of D&D 40 years ago (cite peterson).
 -scholarship just beginning to start
  -peterson
  -documentaries
 -primary sources literally dying off
 -lots of popular material exists (print and pdf)
  -semi-popular material becoming easier to obtain because publishers starting to re-issue back catalogues as PDF
  -very early ephemeral material very hard to obtain
  -domesday book for example
   -a few issues held by libraries [atkatkatk], and while other issues are extant [atkatkatk] they are held privately and essentially inaccessable
   -none that I know of are widely available (except for a few cover scans on the acaeum)

# percieved value
 -early on this was just the hobby of some crazy guys in the mid-west.
  -probably nobody thought that their work would be important
  -all kinds of notes and material that the emergent scholarly community would kill to see was probably just tossed... it's just some crazy little game after all
 -Arneson collection almost lost
 -plagmada
  -after all, could a young James Jaccobs (sp?) have known that his homebrew campaign would later serve as a basis for the default setting for what is currently (by some metrics) the word's most popular roleplaying game?

# collectors
 -centralization
 -value escalation
 -do collectors have appropriate insurance?
  -monetary insurance is one thing... practical insurance is another.
  -there was a story about a colletor scanning his rare items for his own reference before selling them off

# copyright
 -archive.org takedown of magazines
 -sympathetic to individual creators (and *small* companies too)
  -creators have a moral responsability
   -must keep work reasonbly available
   -must provide provisions for release of material in the event of their deaths... none of this 70 years bullshit
 -corporate creators (read *big* companies) I have less sympathy for

# role of traditional institutions
 -It Belongs in a Museum!
 -a few special collections
  -toronto
  -whoever holds the domesday book issues
  -the Strong
  -are there any that are comprehensive even for a subset?
 -Peterson did the right thing by putting the dalhun manuscript in the Strong
 -do libraries/museums value?

# conclusion
 -call for civil disobedience
 -the pirates may save us.
 -save what you have
  -scans are great, but reasonbly hi-res photos will do
  -don't trust cloud services
  -distribute amongst like-minded individuals
  -multiple copies on stable media stored safely/remotely
 -are your originals stored safely?



Ernie Gygax fire

